### ISSUE TITLE
`#gain` isn't too intuitive when used for MIDI velocity

### ISSUE THREAD

**Issue by OscarSouth** [musikinformatik/SuperDirt#120]
On receipt of the note data by the destination, `#gain 0.375` is more or less the minimum possible velocity possible, `#gain 1.26` is pretty much exactly the max and `#gain 1.07` is close enough to the half way point. Most of the usable range is contained in the last few '.1's.

**Comment by yaxu** [comment]
Perhaps we should simply use a `velocity` control instead of `gain`. They're different concepts and I think some synths will have both.

**Comment by OscarSouth** [comment]
Yeah, especially when it comes to sampling where you may have multiple samples mapped to velocity levels, followed by a gain control over the instrument itself. In this case (using MIDI) I'd just be controlling the gain stage by CC, but I think that a `velocity` param that functions as expected would be more intuitive for performing with MIDI.

**Comment by OscarSouth** [comment]
This code converts values between 0 and 1 into a much more sensible velocity scale that can be fed into  the `gain` param (or used to create a `velocity` helper, eg.: `let vel n = gain $ gainScale n`):

```
gainScale n
  | n == 0 = 0.375 
  | otherwise = 
  let (x0, x1, y0, y1) = (0.001, 1, 0.375, 1.26)
      scale = logBase 7
   in y0 + (log n - scale x0) / (log x1 - scale x0) * (y1 - y0)
```

However -- it will return an error when used in a pattern:
```
t>Error in pattern: (==): not supported for patternsCallStack (from HasCallStack): error, called at src/Sound/Tidal/Pattern.hs:386:13 in tidal-1.0.8-AeKVDs6H4fYD0ZxzibMFyU:Sound.Tidal.Pattern
```

Haven't found a solution for this yet, but it is usable (as long as you don't pass a value of 0) by removing the guards.

**Comment by bgold-cosmos** [comment]
SuperDirt is leveraging SC's built-in MIDI event type, which uses "amp" [0-1] to set velocity [0-127].  The issue here is that SD is also automatically doing a nonlinear transform from "gain" to "amp".

One possibility is to just use "amp" from Tidal (`amp = pF "amp"`) when sending MIDI messages, I think that would override any gain settings.  Or possibly `velocity = pF "amp"` if you want the Tidal name for it to be "velocity", though that might be confusing since it would still have the [0-1] range.

**Comment by OscarSouth** [comment]
@bgold-cosmos this works very well and allows user to easily scale the range very well with whatever helper function that choose. I'll be using the simple 0-1 scale myself. Cheers!

If anyone knows how I can get around not being able to use (==) in a function acting on a value contained in a pattern, I'd be interested to know (I know this is a Haskell/tidal thing and not SuperDirt though. It's not necessary here, but I think I'll find some interesting uses for it as a global velocity curve scaler!

**Comment by telephon** [comment]
>SuperDirt is leveraging SC's built-in MIDI event type, which uses "amp" [0-1] to set velocity [0-127]. The issue here is that SD is also automatically doing a nonlinear transform from "gain" to "amp".

`gain` is m a nonlinear scaler for `amp`. It would make sense to add `amp` to tidal, since it is a standard in SD/sclang.

This is the formula used. `~amp = pow(~gain.value, 4) * ~amp.value;`

Currently you can set the overall amplitude for each orbit:

`~dirt.orbits[0].set(\amp, 0.1);`

The `.value` is there so you can use a function or a routine instead of just a value. 

`~dirt.orbits[0].set(\amp, { rrand(0.1, 0.4) });`

Using it from tidal would (could) override the orbit setting.

**Comment by telephon** [comment]
That said, we could rethink the whole amplitude calculation if that would be better.

**Comment by yaxu** [comment]
Ok I've added `amp` for now https://github.com/tidalcycles/Tidal/commit/947aec13a01658eba34390daee0baa145d76b280

**Comment by telephon** [comment]
The question is, should `amp` override `gain`? In the standard sclang library, it looks like this: `amp: #{ ~db.dbamp }`. If you provide `db` it overrides `amp`. 

It would be good to still have a global default amplitude scaling for the orbit.

**Comment by telephon** [comment]
please do feel free to reopen
