### ISSUE TITLE
independent global effects

### ISSUE THREAD

**Issue by telephon** [musikinformatik/SuperDirt#75]
@bgold-cosmos wrote a draft for a different layout of the global effects. We should think together how this should look like.

**Comment by telephon** [comment]
Here is a copy of the comment (from #74):

>I am working on a change to the global effects so that messages don't stomp on each other quite so much.  It makes it much easier to have multiple things going on in a single orbit.
https://github.com/bgold-cosmos/SuperDirt/tree/global-send
Still in progess, and the solution I came up with is kind of ugly, but it seems to be working so far.  I'll have another update to that branch in a few days implementing it for all the global effects.

**Comment by bgold-cosmos** [comment]
Branch is here
 https://github.com/bgold-cosmos/SuperDirt/tree/global-send
Would it be easier to discuss if I submitted a PR?  I've cleaned up some of the ugliest stuff, but it's still not easily extensible.

**Comment by bgold-cosmos** [comment]
I've cleaned up some of the ugliest stuff, but it's still not easily extensible.  Would it be easier to discuss if I submitted a PR?

**Comment by bgold-cosmos** [comment]
OK, so now I'm looking at 1.0-dev.  I really like that things have moved to separate files and it's actually possible to livecode global effects now!  Nice!

But I don't think delaySend is completely doing what I imagined it would do.  This works fine, in the sense that the snare echoes don't get clobbered
```
d1 $ s "sn:2" # delay 1 # delaySend 1 # delayt 0.125 # delayfb 0.9

d2 $ s "~ cp" # delay 1 # delaySend 0 # delayt 0.125 # delayfb 0.9
```
However, since the `delaySend` parameter is used in the (global) delay SynthDef, sounds don't really have an individual send.  It's instead a parameter that controls how much the delay reads from the dryBus, which contains all sounds.  So the following causes unpredictable behavior, since it's ambiguous which delaySend happens first
```
d1 $ s "sn:2" # delay 1 # delaySend 1 # delayt 0.125 # delayfb 0.9

d2 $ s "cp" # delay 1 # delaySend 0 # delayt 0.125 # delayfb 0.9
```

Side note: `delay` seems redundant here, since I don't see that it does anything that delaySend doesn't also do.  Or am I just using this entirely wrong?

**Comment by telephon** [comment]
>However, since the delaySend parameter is used in the (global) delay SynthDef, sounds don't really have an individual send. It's instead a parameter that controls how much the delay reads from the dryBus, which contains all sounds.

Ah yes, of course. We could selectively send to the dry bus, but that would mean one global send parameter for all effects.

So as it turns out, we do not need an extra bus for each effect because of its output, but because of its *input*.

This might only be needed for effects that are meant to have an event based input.

>Side note: delay seems redundant here

I am not sure, I have to look into the tidal synonyms.

**Comment by telephon** [comment]
I think this has been solved, feel free to reopen
